# Generated by Django 2.2.6 on 2019-12-17 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('s', 'saving'), ('o', 'ordinary')], max_length=1, verbose_name='type')),
                ('number', models.CharField(max_length=250, unique=True, verbose_name='number')),
                ('balance', models.IntegerField(default=0, verbose_name='balance')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='current date')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_identification', models.CharField(choices=[('cc', 'citizenship card'), ('fc', 'foreign identity card')], max_length=2, verbose_name='type identification')),
                ('number_identification', models.PositiveIntegerField(verbose_name='number identification')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='current date')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'bank_clients',
            },
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('c', 'consignment'), ('r', 'retirement'), ('4x1000', '4*1000')], max_length=10, verbose_name='type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='value')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='current date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.Account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'db_table': 'bank_accounts_movements',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['type_identification', 'number_identification'], name='bank_client_type_id_f48ec2_idx'),
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Client', verbose_name='client'),
        ),
        migrations.AddIndex(
            model_name='movements',
            index=models.Index(fields=['account'], name='bank_accoun_account_e5af41_idx'),
        ),
        migrations.AddIndex(
            model_name='movements',
            index=models.Index(fields=['account', 'type'], name='bank_accoun_account_83d2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['client'], name='bank_accoun_client__d7b577_idx'),
        ),
    ]
