# Generated by Django 2.2.6 on 2019-12-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='type',
            field=models.CharField(choices=[('c', 'consignment'), ('r', 'retirement'), ('4x1000', '4*1000'), ('ts', 'transfer send'), ('tr', 'transfer received')], max_length=10, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='AuditClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_identification', models.CharField(max_length=2, verbose_name='type identification')),
                ('number_identification', models.PositiveIntegerField(verbose_name='number identification')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='current date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'audit client',
                'verbose_name_plural': 'audits clients',
                'db_table': 'audit_clients',
            },
        ),
        migrations.AddIndex(
            model_name='auditclient',
            index=models.Index(fields=['client'], name='audit_clien_client__cd83fe_idx'),
        ),
    ]
